# Generated by Django 4.2.5 on 2023-09-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teachers_generation", "0002_alter_teacher_teacher_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="teacher_id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
