# Generated by Django 4.2.5 on 2023-10-12 10:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teachers_generation", "0004_alter_teacher_teacher_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Teacher",
            new_name="GenerateTeacher",
        ),
    ]
