# Generated by Django 4.2.5 on 2023-10-06 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teachers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("surname", models.CharField(max_length=30)),
                ("patronymic", models.CharField(max_length=30)),
                ("birth_date", models.DateField()),
                ("subject", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Groups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_name", models.CharField(max_length=100)),
                (
                    "curator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="school.teachers",
                    ),
                ),
            ],
        ),
    ]
