# Generated by Django 4.2.5 on 2023-10-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0001_initial"),
        ("student_generation", "0002_alter_createstudent_student_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="createstudent",
            name="group",
            field=models.ManyToManyField(related_name="student", to="school.groups"),
        ),
    ]
