# Generated by Django 4.2.5 on 2023-10-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_generation", "0005_createstudent_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="createstudent",
            name="phone",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
